query {
  theming {
    config {
      theme
      iconset
      darkMode
      tocPosition
      injectCSS
      injectHead
      injectBody
      primaryColor
      secondaryColor
      headerColor
      footerColor
      successColor
      warningColor
      errorColor
      infoColor
      neutralColor
      chatEnabled
    }
  }
}
