mutation($theme: String!, $iconset: String!, $darkMode: Boolean!, $tocPosition: String, $injectCSS: String, $injectHead: String, $injectBody: String, $primaryColor: String, $headerColor: String, $footerColor: String) {
  theming {
    setConfig(theme: $theme, iconset: $iconset, darkMode: $darkMode, tocPosition: $tocPosition, injectCSS: $injectCSS, injectHead: $injectHead, injectBody: $injectBody, primaryColor: $primaryColor, headerColor: $headerColor, footerColor: $footerColor) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
