query (
  $query: String!
  $filterPages: Boolean
  $filterUpdates: Boolean
  $filterPermissions: Boolean
) {
  pages {
    search(
      query: $query
      filterPages: $filterPages
      filterUpdates: $filterUpdates
      filterPermissions: $filterPermissions
    ) {
      results {
        id
        title
        description
        path
        locale
      }
      suggestions
      totalHits
    }
  }
}
